services:
  db:
    image: "mysql:8.0"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: solidinvoice
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
  app:
    image: "solidinvoice/solidinvoice:latest"
    depends_on:
      - db
    ports:
      - "8765:8765"
    restart: always
    volumes:
      - app_data:/etc/solidinvoice
    environment:
      SOLIDINVOICE_DATABASE_DRIVER: pdo_mysql
      SOLIDINVOICE_DATABASE_HOST: db
      SOLIDINVOICE_DATABASE_PORT: 3306
      SOLIDINVOICE_DATABASE_NAME: solidinvoice
      SOLIDINVOICE_DATABASE_USER: root
      SOLIDINVOICE_DATABASE_PASSWORD:

volumes:
  db_data: {}
  app_data: {}
