name: Automatic Releases

on:
  milestone:
    types:
      - closed

permissions:
  contents: read

jobs:
  release:
    name: "GIT tag, release & create merge-up PR"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf
        with:
          egress-policy: audit
          allowed-endpoints: >
            api.github.com:443
            archive.ubuntu.com:80
            auth.docker.io:443
            bun.sh:443
            github.com:443
            objects.githubusercontent.com:443
            packagist.org:443
            ppa.launchpadcontent.net:443
            production.cloudflare.docker.com:443
            registry-1.docker.io:443
            registry.yarnpkg.com:443
            repo.packagist.org:443
            raw.githubusercontent.com:443
            security.ubuntu.com:80
            uploads.github.com:443

      - name: Derive target branch from milestone title
        id: vars
        run: |
          version="${{ github.event.milestone.title }}"
          [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "Milestone title must be semver"; exit 1; }
          IFS='.' read -r MAJOR MINOR PATCH <<<"$version"
          echo "branch=${MAJOR}.${MINOR}.x" >>"$GITHUB_OUTPUT"   # e.g. 2.3.x
          echo "tag=v${version}" >>"$GITHUB_OUTPUT"

      - name: Checkout
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
        with:
          ref: ${{ steps.vars.outputs.branch }}
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@cf4cade2721270509d5b1c766ab3549210a39a2a
        with:
          php-version: 8.4
          extensions: intl, gd, opcache, mysql, pdo_mysql, soap, zip, :xdebug
          coverage: none

      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Bump version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE: 1
        run: "./scripts/bump_version.sh ${{ steps.vars.outputs.branch }} ${{ github.event.milestone.title }}"

      - name: Release
        run: "./scripts/create_release.sh ${{ github.event.milestone.title }} ${{ github.repository }}"
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          RELEASE: 1
