name: Automatic Releases

on:
  milestone:
    types:
      - closed

permissions:
  contents: read

jobs:
  release:
    name: "GIT tag, release & create merge-up PR"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481
        with:
          egress-policy: audit
          allowed-endpoints: >
            api.github.com:443
            archive.ubuntu.com:80
            auth.docker.io:443
            bun.sh:443
            github.com:443
            objects.githubusercontent.com:443
            packagist.org:443
            ppa.launchpadcontent.net:443
            production.cloudflare.docker.com:443
            registry-1.docker.io:443
            registry.yarnpkg.com:443
            repo.packagist.org:443
            raw.githubusercontent.com:443
            security.ubuntu.com:80
            uploads.github.com:443

      - name: Checkout
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401
        with:
          php-version: 8.4
          extensions: intl, gd, opcache, mysql, pdo_mysql, soap, zip, :xdebug
          coverage: none

      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Bump version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "./scripts/bump_version.sh ${{ github.event.milestone.title }}"

      - name: Release
        run: "./scripts/create_release.sh ${{ github.event.milestone.title }} ${{ github.repository }}"
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
