name: Automatic Releases

on:
  milestone:
    types:
      - closed

jobs:
  release:
    name: "GIT tag, release & create merge-up PR"
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            archive.ubuntu.com:80
            auth.docker.io:443
            github.com:443
            objects.githubusercontent.com:443
            packagist.org:443
            ppa.launchpadcontent.net:443
            production.cloudflare.docker.com:443
            registry-1.docker.io:443
            registry.yarnpkg.com:443
            security.ubuntu.com:80
            uploads.github.com:443

      - name: Checkout
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401
        with:
          php-version: 8.3
          extensions: intl, gd, opcache, mysql, pdo_mysql, soap, zip, :xdebug
          coverage: none

      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
        with:
          node-version: 18

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Bump version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "./scripts/bump_version.sh ${{ github.event.milestone.title }}"

      - name: Release
        uses: laminas/automatic-releases@a6e41a9a66b415667863ecbf06633181fcd9dd77
        with:
          command-name: laminas:automatic-releases:release
        env:
          "GITHUB_TOKEN": ${{ secrets.GITHUB_TOKEN }}
          "SIGNING_SECRET_KEY": ${{ secrets.SIGNING_SECRET_KEY }}
          "GIT_AUTHOR_NAME": ${{ secrets.GIT_AUTHOR_NAME }}
          "GIT_AUTHOR_EMAIL": ${{ secrets.GIT_AUTHOR_EMAIL }}

      - name: Build Release Artifact
        run: "./scripts/build_dist.sh ${{ github.event.milestone.title }} ${{ github.event.milestone.title }}"

      - name: Upload Release Artifact
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          tag_name: ${{ github.event.milestone.title }}
          files: |
            build/dist/SolidInvoice-${{ github.event.milestone.title }}.zip
            build/dist/SolidInvoice-${{ github.event.milestone.title }}.tar.gz

      - name: Login to DockerHub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push standard docker image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          push: true
          context: ./
          file: ./docker/Dockerfile.build
          build-args: |
            SOLIDINVOICE_VERSION=${{ github.event.milestone.title }}
          tags: |
            solidinvoice/solidinvoice:latest
            solidinvoice/solidinvoice:${{ github.event.milestone.title }}

      - name: Build and push full docker image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          push: true
          context: ./
          file: ./docker/Dockerfile.full-build
          build-args: |
            SOLIDINVOICE_VERSION=${{ github.event.milestone.title }}
          tags: |
            solidinvoice/solidinvoice:${{ github.event.milestone.title }}-full

      - name: Create Merge-Up Pull Request
        uses: laminas/automatic-releases@a6e41a9a66b415667863ecbf06633181fcd9dd77
        with:
          command-name: laminas:automatic-releases:create-merge-up-pull-request
        env:
          "GITHUB_TOKEN": ${{ secrets.ORGANIZATION_ADMIN_TOKEN }}
          "SIGNING_SECRET_KEY": ${{ secrets.SIGNING_SECRET_KEY }}
          "GIT_AUTHOR_NAME": ${{ secrets.GIT_AUTHOR_NAME }}
          "GIT_AUTHOR_EMAIL": ${{ secrets.GIT_AUTHOR_EMAIL }}

      - name: Create new milestones
        uses: laminas/automatic-releases@a6e41a9a66b415667863ecbf06633181fcd9dd77
        with:
          command-name: laminas:automatic-releases:create-milestones
        env:
          "GITHUB_TOKEN": ${{ secrets.GITHUB_TOKEN }}
          "SIGNING_SECRET_KEY": ${{ secrets.SIGNING_SECRET_KEY }}
          "GIT_AUTHOR_NAME": ${{ secrets.GIT_AUTHOR_NAME }}
          "GIT_AUTHOR_EMAIL": ${{ secrets.GIT_AUTHOR_EMAIL }}

      - name: Bump version to next dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "./scripts/bump_version_dev.sh"
