name: CS

on: [ pull_request ]

permissions:
  contents: read

jobs:
  ecs:
    name: Coding Standards (PHP)

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            packagist.org:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup PHP
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231
        with:
          php-version: 8.3
          extensions: intl, gd, opcache, mysql, pdo_mysql

      - uses: ramsey/composer-install@0f18aec461938c57720faaf2dba4421bf698cf42 # v3

      - name: Run EasyCodingStandard
        run: bin/ecs check

  composer-normalize:
    name: Composer Normalize

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
        with:
          egress-policy: block
          allowed-endpoints: >
            185.125.188.54:443
            185.125.188.55:443
            185.125.188.59:443
            api.github.com:443
            api.ipify.org:443
            api.launchpad.net:443
            archive.ubuntu.com:80
            azure.archive.ubuntu.com:80
            esm.ubuntu.com:443
            esm.ubuntu.com:80
            github.com:443
            keys.openpgp.org:443
            keyserver.ubuntu.com:443
            motd.ubuntu.com:443
            objects.githubusercontent.com:443
            packages.microsoft.com:443
            packages.microsoft.com:80
            packagist.org:443
            pgp.mit.edu:443
            ppa.launchpad.net:80
            ppa.launchpadcontent.net:443
            ppa.launchpadcontent.net:80
            raw.githubusercontent.com:443
            repo.packagist.org:443
            security.ubuntu.com:443
            security.ubuntu.com:80

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup PHP
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231
        with:
          php-version: 8.3

      - name: Install dependencies
        run: composer install --no-scripts

      - name: Ensure lock file is up to date
        run: composer update --lock --no-scripts

      - name: Run composer normalize
        run: composer normalize --no-update-lock --diff --dry-run

  lint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      statuses: write  # for github/super-linter/slim to mark status of each linter run
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            api.ipify.org:443
            bun.sh:443
            cdn.jsdelivr.net:443
            github.com:443
            objects.githubusercontent.com:443
            packagist.org:443
            registry.npmjs.org:443
            registry.yarnpkg.com:443
            setup-php.com:443

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
            fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231
        with:
          php-version: 8.3
          extensions: intl, gd, opcache, mysql, pdo_mysql, :xdebug

      - uses: ramsey/composer-install@0f18aec461938c57720faaf2dba4421bf698cf42 # v3

      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2

      - run: bun install

      - name: Super-Linter
        uses: github/super-linter/slim@b807e99ddd37e444d189cfd2c2ca1274d8ae8ef1
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: 2.3.x
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSS_FILE_NAME: .stylelintrc.json
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_XML: true
          VALIDATE_MD: true
          VALIDATE_GITLEAKS: true
          VALIDATE_BASH: true
          VALIDATE_PHP_BUILTIN: true
          LINTER_RULES_PATH: .
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_CSS: true
