name: "Nightly Build"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
      - 2.4.x

env:
  SOLIDINVOICE_ENV: prod
  SOLIDINVOICE_DEBUG: 0

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.check.outputs.ref }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Get version
        id: check
        run: |
          echo "ref=nightly" >> "${GITHUB_OUTPUT}"

  build-dist:
    permissions:
      contents: read
    name: Build Assets
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install PHP
        uses: shivammathur/setup-php@20529878ed81ef8e78ddf08b480401e6101a850f
        with:
          coverage: none
          ini-values: memory_limit=-1
          php-version: 8.3

      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2

      - name: Build Release Artifact
        run: "./scripts/build_dist.sh ${{ github.ref_name }} ${{ needs.prepare.outputs.ref }}"
        env:
          RELEASE: 0
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Upload TAR archive
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: SolidInvoice-${{ needs.prepare.outputs.ref || github.ref }}.tar.gz
          path: build/dist/SolidInvoice-${{ needs.prepare.outputs.ref || github.ref }}.tar.gz

  build-linux:
    name: Build Docker Image
    needs: [prepare, build-dist]
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      SOLIDINVOICE_VERSION: ${{ needs.prepare.outputs.ref }}
      PHP_VERSION: 8.3.20
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Login to DockerHub
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
            driver: cloud
            endpoint: "solidinvoice/solidinvoice-app-cloud"
            install: true
            platforms: linux/amd64,linux/arm64

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Download archive
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: SolidInvoice-${{ needs.prepare.outputs.ref || github.ref }}.tar.gz
          path: build/dist

      - name: Build SolidInvoice
        uses: docker/bake-action@37816e747588cb137173af99ab33873600c46ea8 # v6.8.0
        with:
            targets: build-static
            source: .
            push: true
            set: |
                build-static.cache-from=type=gha,scope=php
                build-static.cache-to=type=gha,scope=php,mode=max,ignore-error=true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE: 0
          LATEST: 0
          NIGHTLY: 1
          SOLIDINVOICE_VERSION: ${{ needs.prepare.outputs.ref }}
