name: Security Checker

on: [ pull_request ]

jobs:
  security-checker:
    name: Symfony Security Checker

    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: symfonycorp/security-checker-action@258311ef7ac571f1310780ef3d79fc5abef642b5

