name: Static Analysis

on: [ pull_request ]

jobs:
  phpstan:
    name: PHPStan

    runs-on: ubuntu-latest

    env:
      SOLIDINVOICE_ENV: test
      SOLIDINVOICE_DEBUG: 1

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911
        with:
          egress-policy: block
          allowed-endpoints: >
            185.125.188.54:443
            185.125.188.55:443
            185.125.188.59:443
            api.codecov.io:443
            api.github.com:443
            api.launchpad.net:443
            api.snapcraft.io:443
            archive.ubuntu.com:80
            azure.archive.ubuntu.com:80
            bun.sh:443
            cdn.jsdelivr.net:443
            codecov.io:443
            dl.cloudsmith.io:443
            esm.ubuntu.com:443
            esm.ubuntu.com:80
            getcomposer.org:443
            github.com:443
            keys.openpgp.org:443
            keyserver.ubuntu.com:443
            motd.ubuntu.com:443
            objects.githubusercontent.com:443
            packages.microsoft.com:443
            packages.microsoft.com:80
            packagist.org:443
            pecl.php.net:443
            pecl.php.net:80
            pgp.mit.edu:443
            ppa.launchpad.net:80
            ppa.launchpadcontent.net:443
            ppa.launchpadcontent.net:80
            registry.npmjs.org:443
            registry.yarnpkg.com:443
            release-assets.githubusercontent.com:443
            repo.packagist.org:443
            setup-php.com:443
            security.ubuntu.com:443
            security.ubuntu.com:80
            storage.googleapis.com:443

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Setup PHP
        uses: shivammathur/setup-php@20529878ed81ef8e78ddf08b480401e6101a850f
        with:
          php-version-file: .php-version
          ini-values: date.timezone=Africa/Johannesburg, memory_limit=-1
          extensions: intl, gd, mysql, pdo_mysql, :xdebug

      - uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # v3

      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2

      - run: bun install

      - run: bun run build
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Warm up cache
        run: bin/console cache:warmup -n -vvv -e test

      - name: Run PHPStan
        run: bin/phpstan analyse -c phpstan.test.neon
