name: Unit Tests

on:
    pull_request:
    push:
        branches:
            - 2.3.x

permissions:
    contents: read
    issues: write
    pull-requests: write

jobs:
  unit:
    name: Unit ( PHP ${{ matrix.php }} )

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.3' ]
        coverage: [ false ]
        include:
          - php: '8.2'
            coverage: true
      fail-fast: false

    env:
      SOLIDINVOICE_ENV: test
      SOLIDINVOICE_DEBUG: 0
      PANTHER_NO_HEADLESS: 0
      PANTHER_APP_ENV: test
      PANTHER_NO_SANDBOX: 1
      PANTHER_CHROME_ARGUMENTS: --disable-dev-shm-usage
      COVERAGE: 0
      SOLIDINVOICE_DATABASE_DRIVER: pdo_mysql
      SOLIDINVOICE_DATABASE_HOST: 127.0.0.1
      SOLIDINVOICE_DATABASE_PORT: 3306
      SOLIDINVOICE_DATABASE_NAME: solidinvoice
      SOLIDINVOICE_DATABASE_USER: root
      SOLIDINVOICE_DATABASE_PASSWORD:
      SOLIDINVOICE_DATABASE_VERSION: 8.0

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: solidinvoice_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f
        with:
          egress-policy: block
          allowed-endpoints: >
            accounts.google.com:443
            api.cloudinary.com:443
            api.codecov.io:443
            api.github.com:443
            api.ipify.org:443
            bun.sh:443
            chromedriver.storage.googleapis.com:443
            cli.codecov.io:443
            codecov.io:443
            content-autofill.googleapis.com:443
            content-autofill.googleapis.com:80
            coveralls.io:443
            github.com:443
            googlechromelabs.github.io:443
            ingest.codecov.io:443
            keybase.io:443
            objects.githubusercontent.com:443
            optimizationguide-pa.googleapis.com:443
            optimizationguide-pa.googleapis.com:80
            packagist.org:443
            registry.npmjs.org:443
            registry.yarnpkg.com:443
            repo.packagist.org:443
            storage.googleapis.com:443
            update.googleapis.com:80
            uploader.codecov.io:443

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: haya14busa/action-cond@94f77f7a80cd666cb3155084e428254fea4281fd
        id: coverage_driver
        with:
          cond: ${{ matrix.coverage }}
          if_true: pcov
          if_false: none

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401
        with:
          php-version: ${{ matrix.php }}
          ini-values: date.timezone=Africa/Johannesburg, opcache.enable=1, opcache.enable_cli=1, opcache.memory_consumption=256, opcache.max_accelerated_files=32531, opcache.interned_strings_buffer=8, opcache.validate_timestamps=0, opcache.save_comments=1, opcache.fast_shutdown=0, memory_limit=-1
          extensions: intl, gd, opcache, mysql, pdo_mysql, soap, zip, :xdebug
          coverage: ${{ steps.coverage_driver.outputs.value }}

      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2

      - uses: ramsey/composer-install@0f18aec461938c57720faaf2dba4421bf698cf42 # v3

      - name: Detect browser drivers
        run: bin/bdi detect drivers

      - run: bun install

      - run: bun run build

      - name: Enable code coverage
        if: matrix.coverage
        run: echo "COVERAGE=1" >> $GITHUB_ENV

      - name: Run test suite
        run: |
         mkdir -p build/logs
          if [ "$COVERAGE" = '1' ]; then
            bin/phpunit --coverage-clover build/logs/clover.xml
          else
            bin/phpunit
          fi

      - name: Upload coverage results to Codecov
        uses: codecov/codecov-action@7f8b4b4bde536c465e797be725718b88c5d95e0e
        if: matrix.coverage
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/logs/clover.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true

      - name: Add comment to PR with failure screenshots
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        if: ${{ failure() }}
        env:
            CLOUDINARY_URL: cloudinary://${{ secrets.CLOUDINARY_API_KEY }}:${{ secrets.CLOUDINARY_API_SECRET }}@${{ secrets.CLOUDINARY_CLOUD_NAME }}
            JOB_NAME: Unit ( PHP ${{ matrix.php }} )
        with:
          script: |
            const script = require('./scripts/e2e-failure.js')
            await script({github, context, core})
