name: Unit Tests

on:
    pull_request:
    push:
        branches:
            - 2.3.x
            - 2.4.x

permissions:
    contents: read
    issues: write
    pull-requests: write

jobs:

  phpunit-stress:
    runs-on: ubuntu-latest

    env:
      SOLIDINVOICE_ENV: test
      SOLIDINVOICE_DEBUG: 0
      PANTHER_NO_HEADLESS: 0
      PANTHER_APP_ENV: test
      PANTHER_NO_SANDBOX: 1
      PANTHER_CHROME_ARGUMENTS: --disable-dev-shm-usage
      COVERAGE: 0

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup PHP
        uses: shivammathur/setup-php@20529878ed81ef8e78ddf08b480401e6101a850f
        with:
          php-version: 8.3
          ini-values: date.timezone=Africa/Johannesburg, opcache.enable=1, opcache.enable_cli=1, opcache.memory_consumption=256, opcache.max_accelerated_files=32531, opcache.interned_strings_buffer=8, opcache.validate_timestamps=0, opcache.save_comments=1, opcache.fast_shutdown=0, memory_limit=-1
          extensions: intl, gd, opcache, mysql, pdo_mysql, soap, zip, :xdebug
          coverage: none

      - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2

      - uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # v3

      - name: Detect browser drivers
        run: bin/bdi detect drivers

      - run: bun install

      - run: bun run build

      - name: Stress until failure
        run: |
          set -euo pipefail
          i=0
          while true; do
            i=$((i+1))
            echo "=== RUN $i ==="
            bin/phpunit --debug || exit 1
          done
